### ISSUE TITLE
Animation: type 'MappedListIterable<Sprite, Frame>' is not a subtype of type 'List<Frame>'

### ISSUE THREAD

**Issue by ArielMartinezViera** [renancaraujo/trex-flame#1]
Hello, I download the project to understand how to work Flame. But when I try to compile I receive this error. 

```
E/flutter ( 6433): [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unhandled exception:
E/flutter ( 6433): type 'MappedListIterable<Sprite, Frame>' is not a subtype of type 'List<Frame>'
E/flutter ( 6433): #0      new Animation.spriteList (package:flame/animation.dart:38:10)
E/flutter ( 6433): #1      new RunningTRex (package:trex/game/t_rex/t_rex.dart:113:64)
E/flutter ( 6433): #2      new TRex (package:trex/game/t_rex/t_rex.dart:29:23)
E/flutter ( 6433): #3      new TRexGame (package:trex/game/game.dart:26:16)
E/flutter ( 6433): #4      main (package:trex/main.dart:11:23)
E/flutter ( 6433): <asynchronous suspension>
E/flutter ( 6433): #5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 6433): #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Syncing files to device Android SDK built for x86...         3,8s
```

Do you know how to fix it?

Thanx :)

**Comment by renancaraujo** [comment]
It is related to https://github.com/luanpotter/flame/pull/22
Updating flame will solve this.

**Comment by renancaraujo** [comment]
That should be fixed by now
